### ISSUE TITLE
Checklist after launch Android version

### ISSUE THREAD

**Issue by lex111** [gitpoint/git-point#172]
Based on #2.

The Android version is coming soon :muscle: - this is an important event :boom: after which you can advertise the application (links below). Then more people will know about us, which means there will be more new contributors and even more stars on GitHub :satisfied:

- [x] Update README.md + add new screenshots
- [x] Edit the description of the repository (also add labels: react-native, android, ios, github-client)
- [x] Update the description of the organization
- [x] Update information on the site

Publish information about the application (to get more people to know :raised_hand:)

Add repository as open source app:
- [x] [React-Native-Apps](https://github.com/ReactNativeNews/React-Native-Apps) (PR open: https://github.com/ReactNativeNews/React-Native-Apps/pull/39)
- [x] [open-source-react-native-apps](https://github.com/vitorebatista/open-source-react-native-apps)
- [x] [awesome-react-native](https://github.com/jondot/awesome-react-native#open-source-apps) (PR open: https://github.com/jondot/awesome-react-native/pull/516)
- [x] [open-source-android-apps](https://github.com/pcqpcq/open-source-android-apps) (PR open: https://github.com/pcqpcq/open-source-android-apps/pull/236)

Publish to:
- [x] [Product Hunt](Https://www.producthunt.com/topics/open-source) (already [there](https://www.producthunt.com/posts/gitpoint-3), but it's a pity that you can not add to the category Open Source)
- [x] [Show HN](https://news.ycombinator.com/show)
- [ ] [Hackernoon](https://hackernoon.com/)

If I forgot something, please write in the comments (or update the issue if you are a member). Any suggestions are welcome!

**Comment by andrewda** [comment]
:heart: Thanks for making this checklist! I'm going to open some PR's to the three RN repositories listed here if that works for everyone?

**Comment by lex111** [comment]
@andrewda yes, of course, but only after the release of the Android version, because we could write that it already exists. What do you think?

**Comment by andrewda** [comment]
@lex111 Sure works for me!

**Comment by lex111** [comment]
@andrewda I mean, it's not on Google Play yet.

**Comment by housseindjirdeh** [comment]
I was literally about to write a similar checklist on our gitter channel but this is amazing, thank you so much for this @lex111 literally 2 steps ahead <3

So when I launched GitPoint, my [tweet](https://twitter.com/hdjirdeh/status/884843522301603840) received the most attention by far (and the most traffic). But I also received a good amount from Product Hunt and Reddit. Unfortunately it didn't climb Hacker News as much as I hoped. Once enough attention was coming to the repo - it made GitHub trending and traffic came in beautifully.

I also published it on my LinkedIn feed as well as various Facebook groups. Will do the same again this time around.

In terms of adding to the checklist:

[ ] Twitter
[ ] Social Media groups (Facebook, Google Plus)
[ ] Applicable subreddits (Android/iOS/React Native/Web Dev]
[ ] [MadeWithReact](http://madewithreact.com/http://madewithreact.com/)

If anymore come to mind I'll let you folks know (please feel free to add the above to your list).

Regarding Product Hunt - definitely agree that we should have the app there _but_ it could prove to be a lot more beneficial if a recognized hunter posts our app. Will be happy to reach out to a few beforehand so we can time the release.

**Comment by patw0929** [comment]
Just a friendly reminder, privacy policy page also be needed.

And about the analytics, I have some ideas. I used fabric.io & google analytics in my own apps, it also has react-native packages.

If anything I can help please let me know, I can do it at weekend.

**Comment by housseindjirdeh** [comment]
#169 Privacy Policy is already in :)

Thanks so much @patw0929, I think I'll definitely ask about google analytics integration in the gitter channel over the weekend, appreciate it :pray:
