### ISSUE TITLE
Checklist for tests

### ISSUE THREAD

**Issue by andrewda** [gitpoint/git-point#396]
- [x] #395 
- [x] https://github.com/Gil2015/react-native-table-component/pull/13
- [ ] https://github.com/jaysoo/react-native-parallax-scroll-view/pull/82
- [ ] https://github.com/umhan35/react-native-search-bar/pull/125
- [ ] https://github.com/umhan35/react-native-search-bar/pull/126

**Comment by machour** [comment]
react-native-table-component merged your PR 🕺

**Comment by machour** [comment]
@andrewda i'm all for using these forks until something changes in the original repos.
Do you think we can move forward with tests implementation and have that merged in master?

**Comment by andrewda** [comment]
Yep - I think if these changes aren't merged in, there probably won't be any other significant updates to the package, either. Until they are, I'm fine with just using the forks (though I think I'd prefer if we forked them as the gitpoint organization and used that instead so we can have full control over our dependencies).

**Comment by andrewda** [comment]
^ CC @housseindjirdeh, I think you're the only one with create repo/fork perms

**Comment by machour** [comment]
I was trying rn 0.49 to check out the componentDidCatch for markdown rendering, and stumbled upon the fact that one of rn-app-intro still uses React.PropTypes

Logged an issue for it on its repo.

**Comment by andrewda** [comment]
🎉
